//
//  BooksListModels.swift
//  BooksRUs
//
//  Created by Cathal Farrell on 10/09/2021.
//  Copyright (c) 2021 BooksRUs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  swiftlint:disable nesting

import UIKit

enum BooksList {

	enum FetchBooks {
		struct Request {
		}
		struct Response {
			var books: [Book]?
			var error: Error?
		}
		struct ViewModel {
			var books: [Book]
			var errorMessage: String?
		}
	}
}
