//
//  BooksListWorker.swift
//  BooksRUs
//
//  Created by Cathal Farrell on 10/09/2021.
//  Copyright (c) 2021 BooksRUs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BooksListWorker {

	// MARK: - Get all books from Network

	func getAllBooks(completionHandler:@escaping ([Book]?, Error?) -> Void) {

		BooksService.shared.getBooks { response in
			switch response {
			case .success(let books):
				print("Have books: \(books.count)")
				PersistencyService.shared.addBooks(books: books)
				completionHandler(books, nil)
			case .failure(let err):
				completionHandler(nil, err)
			}
		}
	}

	// MARK: - Get all books from Storage

	func getAllStoredBooks(completionHandler:@escaping ([Book]?, Error?) -> Void) {

		if let persistedBooks = PersistencyService.shared.fetchAllBooks() {
			completionHandler(persistedBooks, nil)
		} else {
			completionHandler(nil, BooksRUsError.noData)
		}

	}
}
