//
//  BooksListPresenter.swift
//  BooksRUs
//
//  Created by Cathal Farrell on 10/09/2021.
//  Copyright (c) 2021 BooksRUs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BooksListPresentationLogic {
	func presentBooks(response: BooksList.FetchBooks.Response)
	func presentStoredBooks(response: BooksList.FetchBooks.Response)
}

class BooksListPresenter: BooksListPresentationLogic {
	weak var viewController: BooksListDisplayLogic?

	// MARK: Present Books From Network

	func presentBooks(response: BooksList.FetchBooks.Response) {
		if let books = response.books {
			let viewModel = BooksList.FetchBooks.ViewModel(books: books)
			viewController?.displayBooks(viewModel: viewModel)
		} else if let error = response.error {
			let viewModel = BooksList.FetchBooks.ViewModel(books: [Book](), errorMessage: error.localizedDescription)
			viewController?.displayError(viewModel: viewModel)
		}
	}

	// MARK: Present Books From Storage

	func presentStoredBooks(response: BooksList.FetchBooks.Response) {
		if let books = response.books {
			let viewModel = BooksList.FetchBooks.ViewModel(books: books)
			viewController?.displayStoredBooks(viewModel: viewModel)
		} else if let error = response.error {
			let viewModel = BooksList.FetchBooks.ViewModel(books: [Book](), errorMessage: error.localizedDescription)
			viewController?.displayStoredBooksError(viewModel: viewModel)
		}
	}
}
